import type { Metadata } from "next"
import { Roboto } from "next/font/google"

import Providers from "./providers"

import "~/styles/globals.css"

import { getServerAuthSession } from "~/server/auth"

const sans = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerAuthSession()
  return (
    <html lang="en">
      <body
        className={sans.className}
      >
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  )
}
